version: "2.4"
services:
  model-catalog:
    image: nexus.dataspartan.com:9443/turintech/evoml-releases/model-catalog:develop
    build:
      context: ./
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
      - zipkin
    container_name: model-catalog
    restart: always
    ports:
      - ${MODEL_CATALOG_PORT}:${MODEL_CATALOG_PORT}
    networks:
      - model-catalog-network
  postgres:
    image: 'postgres:latest'
    container_name: model-catalog-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA:/data/postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/data/postgres
    networks:
      - model-catalog-network
  zipkin:
    image: 'openzipkin/zipkin:latest'
    container_name: model-catalog-zipkin
    ports:
      - '9411'
    networks:
      - model-catalog-network

volumes:
  postgres:

networks:
  model-catalog-network: