version: "2.4"
services:
  model-catalog:
    image: nexus.dataspartan.com:9443/turintech/evoml-releases/model-catalog:develop
    build:
      context: ./
      dockerfile: docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    container_name: model-catalog
    restart: always
    ports:
      - ${MODEL_CATALOG_PORT}:${MODEL_CATALOG_PORT}
    networks:
      - model-catalog-network
    healthcheck:
      test: curl --fail http://localhost:8081/actuator/health/db || exit 1
#      test: [ "CMD", "bash", "-c", "./application/liquibase-check.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: 'postgres:latest'
    container_name: model-catalog-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/data/postgres
    networks:
      - model-catalog-network

volumes:
  postgres:

networks:
  model-catalog-network: