version: "2.4"
services:
  model-catalog:
    image: nexus.dataspartan.com:9443/turintech/evoml-releases/model-catalog:develop
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: model-catalog
    restart: always
    ports:
      - 8081:8081
  postgres:
    image: 'postgres:latest'
    container_name: model-catalog-postgres
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    restart: always
    ports:
      - 5432:5432
  zipkin:
    image: 'openzipkin/zipkin:latest'
    container_name: model-catalog-zipkin
    ports:
      - '9411'
